# Header
menu:
  主页: /
  所有文章: /archives
  向我打赏: /donate
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/lifesider"
  weibo: "http://weibo.com/lifesider1"
  zhihu: "http://www.zhihu.com/people/lifesider"
  xueqiu: "http://xueqiu.com/lifesider"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
baidu_analytics: a6b512c7047c4baa802f36a0b351616a
favicon: /images/avatar.png

#你的头像url
avatar: /images/avatar.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: lifesider
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  信笔论金: http://xinbee.cn
  Dorid: http://dorid.me
  Andrew Adams: http://people.csail.mit.edu/abadams/
  VideoLan: http://www.videolan.org/
  Jia Jiaya: http://www.cse.cuhk.edu.hk/~leojia/
  ImageShop: http://www.cnblogs.com/Imageshop/
  Disney: http://www.disneyresearch.com/
  IPOL: http://www.ipol.im/
  #奥巴马的博客: http://localhost:4000/
  #卡卡的美丽传说: http://localhost:4000/
  #本泽马的博客: http://localhost:4000/
  #吉格斯的博客: http://localhost:4000/
  #习大大大不同: http://localhost:4000/
  #托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 投学于数学专业，从业于IT行业，资深广播电视行业参与者，热爱图像处理与机器视觉研究，热爱简单即美的数学，热爱浩瀚无际的宇宙，热爱生活，热爱这土地。